# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 528b459687f63752c4ae0dccf218991238c41ae57390bcfbd65633e928b9c1f981e9f3d288796e24c1ab459fd291e4c902f3dd1b352321bb4ed6413cde1973b4

test:
  secret_key_base: 53bc2c2005d9ae2352e9855891746ead4cc6911db725077ebf0511bede948244b1116d184a97a51fbcc8927d62fe2d4d7f53911a1a25a86fe148e312d0487d71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
